global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api_gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Catalog Service
  - job_name: 'catalog'
    static_configs:
      - targets: ['catalog:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Cart Service
  - job_name: 'cart'
    static_configs:
      - targets: ['cart:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:4318']
    metrics_path: '/metrics'
    scrape_interval: 15s
